/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const CancellationData = IDL.Record({
  'createdAt' : Time,
  'orderId' : IDL.Text,
  'partnerId' : IDL.Text,
  'charge' : IDL.Float64,
  'reason' : IDL.Text,
});
export const EarningsData = IDL.Record({
  'createdAt' : Time,
  'partnerId' : IDL.Text,
  'paymentType' : IDL.Variant({ 'cod' : IDL.Null, 'online' : IDL.Null }),
  'amount' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
  'returned' : IDL.Null,
});
export const OrderData = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : Time,
  'orderType' : IDL.Text,
  'partnerId' : IDL.Text,
  'updatedAt' : Time,
  'charges' : IDL.Float64,
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'car' : IDL.Null,
  'van' : IDL.Null,
  'truck' : IDL.Null,
  'bike' : IDL.Null,
});
export const DocumentRef = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'contentType' : IDL.Text,
  'name' : IDL.Text,
});
export const PartnerData = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'vehicleType' : VehicleType,
  'documents' : IDL.Vec(DocumentRef),
  'name' : IDL.Text,
  'createdAt' : Time,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
});
export const ReturnData = IDL.Record({
  'createdAt' : Time,
  'orderId' : IDL.Text,
  'partnerId' : IDL.Text,
  'charge' : IDL.Float64,
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'partnerId' : IDL.Text,
});
export const OrderDataIdentifier = IDL.Text;
export const PartnerDataIdentifier = IDL.Text;

export const idlService = IDL.Service({
  'addCancellation' : IDL.Func([CancellationData], [], []),
  'addEarnings' : IDL.Func([EarningsData], [], []),
  'addOrder' : IDL.Func([OrderData], [], []),
  'addPartner' : IDL.Func([PartnerData], [], []),
  'addReturn' : IDL.Func([ReturnData], [], []),
  'getAllPartners' : IDL.Func([], [IDL.Vec(PartnerData)], ['query']),
  'getAvailableOrders' : IDL.Func([], [IDL.Vec(OrderData)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCancellations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CancellationData)],
      ['query'],
    ),
  'getEarnings' : IDL.Func([IDL.Text], [IDL.Vec(EarningsData)], ['query']),
  'getOrder' : IDL.Func([OrderDataIdentifier], [OrderData], ['query']),
  'getOrderCountByType' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getPartner' : IDL.Func([PartnerDataIdentifier], [PartnerData], ['query']),
  'getPartnerOrders' : IDL.Func([IDL.Text], [IDL.Vec(OrderData)], ['query']),
  'getReturns' : IDL.Func([IDL.Text], [IDL.Vec(ReturnData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantAdmin' : IDL.Func([IDL.Principal], [], []),
  'registerUser' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([OrderDataIdentifier, OrderStatus], [], []),
  'updatePartnerDocuments' : IDL.Func(
      [PartnerDataIdentifier, IDL.Vec(DocumentRef)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const CancellationData = IDL.Record({
    'createdAt' : Time,
    'orderId' : IDL.Text,
    'partnerId' : IDL.Text,
    'charge' : IDL.Float64,
    'reason' : IDL.Text,
  });
  const EarningsData = IDL.Record({
    'createdAt' : Time,
    'partnerId' : IDL.Text,
    'paymentType' : IDL.Variant({ 'cod' : IDL.Null, 'online' : IDL.Null }),
    'amount' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
    'returned' : IDL.Null,
  });
  const OrderData = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : Time,
    'orderType' : IDL.Text,
    'partnerId' : IDL.Text,
    'updatedAt' : Time,
    'charges' : IDL.Float64,
  });
  const Status = IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null });
  const VehicleType = IDL.Variant({
    'car' : IDL.Null,
    'van' : IDL.Null,
    'truck' : IDL.Null,
    'bike' : IDL.Null,
  });
  const DocumentRef = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'contentType' : IDL.Text,
    'name' : IDL.Text,
  });
  const PartnerData = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'vehicleType' : VehicleType,
    'documents' : IDL.Vec(DocumentRef),
    'name' : IDL.Text,
    'createdAt' : Time,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const ReturnData = IDL.Record({
    'createdAt' : Time,
    'orderId' : IDL.Text,
    'partnerId' : IDL.Text,
    'charge' : IDL.Float64,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'partnerId' : IDL.Text });
  const OrderDataIdentifier = IDL.Text;
  const PartnerDataIdentifier = IDL.Text;
  
  return IDL.Service({
    'addCancellation' : IDL.Func([CancellationData], [], []),
    'addEarnings' : IDL.Func([EarningsData], [], []),
    'addOrder' : IDL.Func([OrderData], [], []),
    'addPartner' : IDL.Func([PartnerData], [], []),
    'addReturn' : IDL.Func([ReturnData], [], []),
    'getAllPartners' : IDL.Func([], [IDL.Vec(PartnerData)], ['query']),
    'getAvailableOrders' : IDL.Func([], [IDL.Vec(OrderData)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCancellations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CancellationData)],
        ['query'],
      ),
    'getEarnings' : IDL.Func([IDL.Text], [IDL.Vec(EarningsData)], ['query']),
    'getOrder' : IDL.Func([OrderDataIdentifier], [OrderData], ['query']),
    'getOrderCountByType' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getPartner' : IDL.Func([PartnerDataIdentifier], [PartnerData], ['query']),
    'getPartnerOrders' : IDL.Func([IDL.Text], [IDL.Vec(OrderData)], ['query']),
    'getReturns' : IDL.Func([IDL.Text], [IDL.Vec(ReturnData)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantAdmin' : IDL.Func([IDL.Principal], [], []),
    'registerUser' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([OrderDataIdentifier, OrderStatus], [], []),
    'updatePartnerDocuments' : IDL.Func(
        [PartnerDataIdentifier, IDL.Vec(DocumentRef)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };