/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CancellationData {
  'createdAt' : Time,
  'orderId' : string,
  'partnerId' : string,
  'charge' : number,
  'reason' : string,
}
export interface DocumentRef {
  'id' : string,
  'url' : string,
  'contentType' : string,
  'name' : string,
}
export interface EarningsData {
  'createdAt' : Time,
  'partnerId' : string,
  'paymentType' : { 'cod' : null } |
    { 'online' : null },
  'amount' : number,
}
export interface OrderData {
  'id' : string,
  'status' : OrderStatus,
  'createdAt' : Time,
  'orderType' : string,
  'partnerId' : string,
  'updatedAt' : Time,
  'charges' : number,
}
export type OrderDataIdentifier = string;
export type OrderStatus = { 'cancelled' : null } |
  { 'outForDelivery' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null } |
  { 'accepted' : null } |
  { 'returned' : null };
export interface PartnerData {
  'id' : string,
  'status' : Status,
  'vehicleType' : VehicleType,
  'documents' : Array<DocumentRef>,
  'name' : string,
  'createdAt' : Time,
  'rating' : number,
  'phone' : string,
}
export type PartnerDataIdentifier = string;
export interface ReturnData {
  'createdAt' : Time,
  'orderId' : string,
  'partnerId' : string,
  'charge' : number,
  'reason' : string,
}
export type Status = { 'active' : null } |
  { 'inactive' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'partnerId' : string }
export type VehicleType = { 'car' : null } |
  { 'van' : null } |
  { 'truck' : null } |
  { 'bike' : null };
export interface _SERVICE {
  'addCancellation' : ActorMethod<[CancellationData], undefined>,
  'addEarnings' : ActorMethod<[EarningsData], undefined>,
  'addOrder' : ActorMethod<[OrderData], undefined>,
  'addPartner' : ActorMethod<[PartnerData], undefined>,
  'addReturn' : ActorMethod<[ReturnData], undefined>,
  'getAllPartners' : ActorMethod<[], Array<PartnerData>>,
  'getAvailableOrders' : ActorMethod<[], Array<OrderData>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCancellations' : ActorMethod<[string], Array<CancellationData>>,
  'getEarnings' : ActorMethod<[string], Array<EarningsData>>,
  'getOrder' : ActorMethod<[OrderDataIdentifier], OrderData>,
  'getOrderCountByType' : ActorMethod<[], Array<[string, bigint]>>,
  'getPartner' : ActorMethod<[PartnerDataIdentifier], PartnerData>,
  'getPartnerOrders' : ActorMethod<[string], Array<OrderData>>,
  'getReturns' : ActorMethod<[string], Array<ReturnData>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAdmin' : ActorMethod<[Principal], undefined>,
  'registerUser' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<
    [OrderDataIdentifier, OrderStatus],
    undefined
  >,
  'updatePartnerDocuments' : ActorMethod<
    [PartnerDataIdentifier, Array<DocumentRef>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];