/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const CancellationData = IDL.Record({
  'createdAt' : Time,
  'orderId' : IDL.Text,
  'partnerId' : IDL.Text,
  'charge' : IDL.Float64,
  'reason' : IDL.Text,
});
export const EarningsData = IDL.Record({
  'createdAt' : Time,
  'partnerId' : IDL.Text,
  'paymentType' : IDL.Variant({ 'cod' : IDL.Null, 'online' : IDL.Null }),
  'amount' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
  'returned' : IDL.Null,
});
export const OrderData = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : Time,
  'orderType' : IDL.Text,
  'partnerId' : IDL.Text,
  'updatedAt' : Time,
  'charges' : IDL.Float64,
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'car' : IDL.Null,
  'van' : IDL.Null,
  'truck' : IDL.Null,
  'bike' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PartnerData = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'vehicleType' : VehicleType,
  'documents' : IDL.Vec(ExternalBlob),
  'name' : IDL.Text,
  'createdAt' : Time,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
});
export const ReturnData = IDL.Record({
  'createdAt' : Time,
  'orderId' : IDL.Text,
  'partnerId' : IDL.Text,
  'charge' : IDL.Float64,
  'reason' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'partnerId' : IDL.Text,
});
export const OrderDataIdentifier = IDL.Text;
export const PartnerDataIdentifier = IDL.Text;

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCancellation' : IDL.Func([CancellationData], [], []),
  'addEarnings' : IDL.Func([EarningsData], [], []),
  'addOrder' : IDL.Func([OrderData], [], []),
  'addPartner' : IDL.Func([PartnerData], [], []),
  'addReturn' : IDL.Func([ReturnData], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPartners' : IDL.Func([], [IDL.Vec(PartnerData)], ['query']),
  'getAvailableOrders' : IDL.Func([], [IDL.Vec(OrderData)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCancellations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CancellationData)],
      ['query'],
    ),
  'getEarnings' : IDL.Func([IDL.Text], [IDL.Vec(EarningsData)], ['query']),
  'getOrder' : IDL.Func([OrderDataIdentifier], [OrderData], ['query']),
  'getOrderCountByType' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getPartner' : IDL.Func([PartnerDataIdentifier], [PartnerData], ['query']),
  'getPartnerOrders' : IDL.Func([IDL.Text], [IDL.Vec(OrderData)], ['query']),
  'getReturns' : IDL.Func([IDL.Text], [IDL.Vec(ReturnData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([OrderDataIdentifier, OrderStatus], [], []),
  'updatePartnerDocuments' : IDL.Func(
      [PartnerDataIdentifier, IDL.Vec(ExternalBlob)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const CancellationData = IDL.Record({
    'createdAt' : Time,
    'orderId' : IDL.Text,
    'partnerId' : IDL.Text,
    'charge' : IDL.Float64,
    'reason' : IDL.Text,
  });
  const EarningsData = IDL.Record({
    'createdAt' : Time,
    'partnerId' : IDL.Text,
    'paymentType' : IDL.Variant({ 'cod' : IDL.Null, 'online' : IDL.Null }),
    'amount' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
    'returned' : IDL.Null,
  });
  const OrderData = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : Time,
    'orderType' : IDL.Text,
    'partnerId' : IDL.Text,
    'updatedAt' : Time,
    'charges' : IDL.Float64,
  });
  const Status = IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null });
  const VehicleType = IDL.Variant({
    'car' : IDL.Null,
    'van' : IDL.Null,
    'truck' : IDL.Null,
    'bike' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PartnerData = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'vehicleType' : VehicleType,
    'documents' : IDL.Vec(ExternalBlob),
    'name' : IDL.Text,
    'createdAt' : Time,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const ReturnData = IDL.Record({
    'createdAt' : Time,
    'orderId' : IDL.Text,
    'partnerId' : IDL.Text,
    'charge' : IDL.Float64,
    'reason' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'partnerId' : IDL.Text });
  const OrderDataIdentifier = IDL.Text;
  const PartnerDataIdentifier = IDL.Text;
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCancellation' : IDL.Func([CancellationData], [], []),
    'addEarnings' : IDL.Func([EarningsData], [], []),
    'addOrder' : IDL.Func([OrderData], [], []),
    'addPartner' : IDL.Func([PartnerData], [], []),
    'addReturn' : IDL.Func([ReturnData], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPartners' : IDL.Func([], [IDL.Vec(PartnerData)], ['query']),
    'getAvailableOrders' : IDL.Func([], [IDL.Vec(OrderData)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCancellations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CancellationData)],
        ['query'],
      ),
    'getEarnings' : IDL.Func([IDL.Text], [IDL.Vec(EarningsData)], ['query']),
    'getOrder' : IDL.Func([OrderDataIdentifier], [OrderData], ['query']),
    'getOrderCountByType' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getPartner' : IDL.Func([PartnerDataIdentifier], [PartnerData], ['query']),
    'getPartnerOrders' : IDL.Func([IDL.Text], [IDL.Vec(OrderData)], ['query']),
    'getReturns' : IDL.Func([IDL.Text], [IDL.Vec(ReturnData)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([OrderDataIdentifier, OrderStatus], [], []),
    'updatePartnerDocuments' : IDL.Func(
        [PartnerDataIdentifier, IDL.Vec(ExternalBlob)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };